#!/usr/bin/fish

mkdir -p $HOME/.puppet/r10k
set R10KYAML $HOME/.puppet/r10k/r10k.yaml
printf ":cachedir: $HOME/.puppet/cache/r10k\n" > $R10KYAML
printf ":sources:\n" >> $R10KYAML
printf "  :dotfiles:\n" >> $R10KYAML
printf "    remote: https://github.com/drgraham/dotfiles.git\n" >> $R10KYAML
printf "    basedir: $HOME/.puppet/code/environments\n" >> $R10KYAML

r10k deploy environment -c $R10KYAML -pv info master
pushd $HOME/.puppet/code/environments/master
puppet apply -t --environment master --modulepath modules:dist:site manifests/site.pp
popd
